// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseIcon: typeof import('./src/components/base/BaseIcon.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    BaseLoadingIcon: typeof import('./src/components/base/BaseLoadingIcon.vue')['default']
    ConnectWallet: typeof import('./src/components/ConnectWallet.vue')['default']
    VideoSlider: typeof import('./src/components/VideoSlider.vue')['default']
  }
}

export {}
