// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseDiagram: typeof import('./src/components/base/BaseDiagram.vue')['default']
    BaseIcon: typeof import('./src/components/base/BaseIcon.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    BaseLoadingIcon: typeof import('./src/components/base/BaseLoadingIcon.vue')['default']
    Bottle: typeof import('./src/components/Bottle.vue')['default']
    BottleSelect: typeof import('./src/components/BottleSelect.vue')['default']
    ConnectWallet: typeof import('./src/components/ConnectWallet.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InfoCard: typeof import('./src/components/InfoCard.vue')['default']
    Slider: typeof import('./src/components/Slider.vue')['default']
    SocialList: typeof import('./src/components/lists/SocialList.vue')['default']
    SortSelect: typeof import('./src/components/SortSelect.vue')['default']
    VideoSlider: typeof import('./src/components/VideoSlider.vue')['default']
    Web3Button: typeof import('./src/components/Web3Button.vue')['default']
  }
}

export { }
