// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/base/BaseButton.vue')['default']
    BaseIcon: typeof import('./components/base/BaseIcon.vue')['default']
    BaseInput: typeof import('./components/base/BaseInput.vue')['default']
    BaseLoadingIcon: typeof import('./components/base/BaseLoadingIcon.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
  }
}

export {}
